In [2]:
import pandas as pd
df=pd.read_csv('lyrics.csv')
df

,Year,love,baby,yeah,girl,heart,night,dance,feel,world,...,dream,way,stay,eyes,time,forever,boy,kiss,run,rain
0,2005,90,156,77,142,172,101,148,68,56,...,120,93,176,172,192,173,97,128,73,183
1,2006,182,140,59,69,138,132,138,63,80,...,87,66,180,160,174,153,102,134,75,179
2,2007,156,84,196,104,56,187,80,124,193,...,141,96,151,161,56,87,73,203,73,140
3,2008,123,112,194,180,86,160,75,117,131,...,124,128,126,129,94,158,187,86,77,92
4,2009,133,111,154,103,69,78,120,153,200,...,140,145,133,129,153,164,82,78,55,72
5,2010,138,151,107,152,109,199,135,99,153,...,191,135,151,122,99,160,91,68,74,81
6,2011,154,156,97,153,112,200,164,125,193,...,193,110,109,114,137,138,102,98,72,88
7,2012,150,91,95,115,86,177,117,94,186,...,181,128,104,99,111,122,93,91,88,73
8,2013,148,117,107,120,84,198,77,98,156,...,150,104,99,101,122,143,119,100,75,88
9,2014,137,107,57,91,83,160,122,101,138,...,122,98,125,115,96,137,111,78,63,87
10,2015,126,91,100,89,65,151,81,93,150,...,129,114,109,132,105,120,130,87,61,91
11,2016,180,137,109,90,55,169,84,102,193,...,158,107,132,125,116,134,101,99,79,77
12,2017,170,152,96,118,111,174,126,108,182,...,158,107,132,124,132,134,113,116,79,86
13,2018,108,70,198,162,74,77,74,77,148,...,165,51,52,141,130,121,121,67,64,55